name: Deployment 1
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Install Dependencies
          run: npm ci
        - name: Run Lint
          run: npm run lint
        - name: Run Test
          run: npm run test
        - name: Build code
          run: npm run build
        - name: Deploy code
          run: echo "Deploying..."
